# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Data for the cat generator."""

CAT_NAMES = [
    "Abby",
    "Angel",
    "Annie",
    "Apple Blossom",
    "Ash",
    "Athena",
    "Baby",
    "Backpack",
    "Bailey",
    "Bandit",
    "Bear",
    "Belle",
    "Biscuit",
    "Blue",
    "Bob",
    "Boo",
    "Boots",
    "Brownie",
    "Bubba",
    "Bud",
    "Buddy",
    "Buster",
    "Buttercup",
    "Cali",
    "Callie",
    "Calvin",
    "Cantaloupe",
    "Casper",
    "Cat",
    "Charlie",
    "Chester",
    "Chloe",
    "Chocolate",
    "Cleo",
    "Clover",
    "Clyde",
    "Coco",
    "Cookie",
    "Cooper",
    "Cuddles",
    "Daffodil",
    "Dahlia",
    "Daisy",
    "Deidra",
    "Django",
    "Duchess",
    "Duke",
    "Dusty",
    "Ella",
    "Emma",
    "Felix",
    "Fiona",
    "Fluffer",
    "Fluffy",
    "Frank",
    "Frankie",
    "George",
    "Ginger",
    "Gizmo",
    "Gordon",
    "Gracie",
    "Gus",
    "Ham",
    "Harley",
    "Hazel",
    "Iris",
    "Izzy",
    "Jack",
    "Jackson",
    "Jasmine",
    "Jasper",
    "Jax",
    "Jerma",
    "Joey",
    "June",
    "Kali",
    "Kiki",
    "Kitten",
    "Kitty",
    "Layla",
    "Layne",
    "Lemon",
    "Leo",
    "Lilly",
    "Lily",
    "Lola",
    "Lollipop",
    "Louie",
    "Lucky",
    "Lucy",
    "Lulu",
    "Luna",
    "Macaron",
    "Maggie",
    "Magnolia",
    "Marigold",
    "Marley",
    "Marshmallow",
    "Max",
    "Melissa",
    "Merengue",
    "Mia",
    "Midnight",
    "Millie",
    "Milo",
    "Mimi",
    "Minnie",
    "Mischief",
    "Missy",
    "Misty",
    "Mittens",
    "Mochi",
    "Molly",
    "Moose",
    "Muffin",
    "Murphy",
    "Nala",
    "Nancy",
    "Oliver",
    "Olivia",
    "Ollie",
    "Oreo",
    "Oscar",
    "Patches",
    "Paw Paw",
    "Peanut",
    "Peanut Butter",
    "Penny",
    "Pepper",
    "Pickles",
    "Piper",
    "Pizza",
    "Pop",
    "Poppy",
    "Precious",
    "Primrose",
    "Princess",
    "Pumpkin",
    "Rascal",
    "Remi",
    "Riley",
    "Rocky",
    "Romeo",
    "Rose",
    "Rosie",
    "Ruby",
    "Sadie",
    "Salad",
    "Salem",
    "Sam",
    "Samantha",
    "Sammy",
    "Sasha",
    "Sassy",
    "Scooter",
    "Scout",
    "Shadow",
    "Sheba",
    "Shortcake",
    "Simba",
    "Simon",
    "Smokey",
    "Snickers",
    "Snowball",
    "Snuggles",
    "Socks",
    "Sophie",
    "Spooky",
    "Sugar",
    "Sunny",
    "Sushi",
    "Taco",
    "Tart",
    "Tartlet",
    "Teddy",
    "Tegan",
    "Theo",
    "Thistle",
    "Tiger",
    "Tinkerbell",
    "Toby",
    "Trouble",
    "Tucker",
    "Turnip",
    "Walrus",
    "Walter",
    "Whiskers",
    "Will",
    "Willow",
    "Ziggy",
    "Zoe",
    "Zoey",
]

CAT_PREFIXES = [
    "Baby",
    "Baby",
    "Big",
    "Big",
    "Brother",
    "Captain",
    "Chancellor",
    "Count",
    "Detective",
    "Doctor",
    "Duke",
    "Father",
    "Fluffy",
    "Fluffy",
    "General",
    "King",
    "Lady",
    "Lieutenant",
    "Little",
    "Little",
    "Lord",
    "Madam",
    "Mama",
    "Miss",
    "Mr",
    "Ms",
    "Professor",
    "Queen",
    "Sergeant",
    "Sir",
    "Tiny",
    "Tiny",
]

CAT_SUFFIXES = [
    "Alpha",
    "Alpha",
    "Beta",
    "Beta",
    "I",
    "II",
    "III",
    "IV",
    "IV",
    "Jr",
    "Jr",
    "Jr",
    "Jr",
    "Jr",
    "Jr",
    "Jr",
    "Jr",
    "Jr",
    "Jr",
    "Prime",
    "Prime",
    "Sr",
    "Sr",
    "Sr",
    "Sr",
    "Sr",
    "Sr",
    "Sr",
    "Sr",
    "Sr",
    "Sr",
    "V",
    "VI",
    "VII",
    "VIII",
    "X",
    "XI",
    "XIII",
    "XIV",
    "XIX",
    "XV",
    "XVI",
    "XVII",
    "XVIII",
    "XX",
]

CAT_DESCRIPTORS = [
    "anime",
    "anxious",
    "arsonist",
    "aspiring",
    "average",
    "awesome",
    "based",
    "bassist",
    "bored",
    "capitalist",
    "coffee addict",
    "communist",
    "content",
    "cool",
    "couch",
    "criminal",
    "demanding",
    "depressed",
    "disappointing",
    "dreamer",
    "drummer",
    "excellent",
    "explorer",
    "familiar",
    "fluffy",
    "gamer",
    "generic",
    "ghost",
    "great",
    "guitarist",
    "helpful",
    "hit",
    "hostile",
    "mecha",
    "normal",
    "outdoor",
    "professional",
    "programmer",
    "sassy",
    "singer",
    "sleepy",
    "smol",
    "smug",
    "stray",
    "superstar",
    "terminally online",
    "tired",
    "top tier",
    "unusual",
    "vampire",
    "warm",
    "wonderful",
]

CAT_LIKES_DISLIKES = [
    '"intellectual" debate',
    "Carly Rae Jepsen",
    "IPAs",
    "June",
    "Mexican food",
    "Mondays",
    "Nancy Drew",
    "alcohol",
    "banjos",
    "beaches",
    "building",
    "cantaloupe",
    "card games",
    "casual games",
    "catnip",
    "cleaning",
    "computers",
    "cooking",
    "djent",
    "dogs",
    "exercise",
    "feet",
    "fortnite",
    "furries",
    "hardcore games",
    "intellectual debate",
    "jazz",
    "lasagna",
    "maths",
    "meat",
    "metal",
    "phone calls",
    "physics",
    "pineapple on pizza",
    "public transportation",
    "punk rock",
    "reading",
    "rollback netcode",
    "scary movies",
    "shanties",
    "shopping",
    "spices",
    "sugary drinks",
    "surreal memes",
    "sweets",
    'the "In The Feedback" riff',
    "the British",
    "the MCU",
    "the short stories of Italo Calvino",
    "travelling",
]

CAT_HOBBIES = [
    "LARPing",
    "baking edibles for Halloween",
    "begging Discord mods for a vanity color role",
    "being a disappointment",
    "being a landlord apologist on Twitter",
    "being anxious",
    "being cute",
    "being weirdly into knives",
    "building an entire online persona around weird politics",
    "building guitars out of scrapwood",
    "bullying cryptobros on Twitter",
    "collecting NFTs",
    "collecting rare memes",
    "commissioning NSFW art",
    "committing arson",
    "conlanging",
    "debating whether shanties are truly shantic",
    "defacing Wikipedia",
    "defending nu-Trek online",
    "destroying furniture",
    "doing Asana admin",
    "doing community service",
    "drinking toilet water",
    "drinking way too much Monster Energy",
    "dumping the litter box over the entire apartment",
    "eating breakfast sandwiches",
    "eating chocolate",
    "editing kpop fancams",
    "feeling sad",
    "fishing",
    "flirting (platonically)",
    "getting cancelled for Blaseball RP discourse",
    "getting cancelled for liking boats",
    "getting forklift certified",
    "getting swole",
    "giving unsolicited advice to people in #drop-demos",
    "grinding Final Fantasy XIV dungeons",
    "having a gender crisis",
    "in therapy",
    "learning Toki Pona",
    "learning Unity",
    "learning to code",
    "listening to true crime podcasts",
    "looking at gear $he$ can't afford",
    "looking for obscure cassettes on Bandcamp",
    "making EDM remixes of shanties for TikTok",
    "making breakcore",
    "making long grilled cheese",
    "making melty bread",
    "meowing loudly",
    "napping",
    "negotiating salary raises",
    "not practicing an instrument",
    "on personal improvement",
    "ordering clothes from Etsy",
    "phishing old ladies",
    "playing D&D",
    "playing Nancy Drew games",
    "playing bass",
    "playing drums",
    "playing guitar",
    "playing poker",
    "playing sax",
    "practicing lockpicking",
    "practicing witchcraft",
    "pretending to be a dog",
    "pretending to work from home",
    "pretening to be a human in online chatrooms",
    "reading papers about gonorrhea",
    "reading the SCP wiki",
    "reporting people on Twitter for having different opinions",
    "retweeting articles $he$ didn't read",
    "retweeting strangers' selfies",
    "reviewing fast food",
    "rickrolling Redditors",
    "rightclicking NFTs",
    "running Discord phishing scams",
    "running a credit card stealing operation",
    "scouring Ebay for rare MTG cards",
    "servin' sweet dunks",
    "shitposting on Twitter",
    "singing",
    "sitting muted in voice channels",
    "skateboarding",
    "sleeping",
    "smuggling drugs across the border",
    "stealing Unity assets",
    "streaming on Twitch",
    "taking long walks",
    "tasting whisky",
    "thirstposting (platonically)",
    "trading crypto",
    "trading stock",
    "vaping",
    "watching Defcon talks",
    "watching Minecraft youtubers",
    "watching Roguelike Celebration talks",
    "watching birds",
    "watching old Jerma985 VODs",
    "wearing human ears",
    "working from home",
    'yelling at people for calling roguelites "roguelikes"',
]

CAT_PRONOUNS = [
    "cat,cat,cats,catself,false",
    "he,him,his,himself,false",
    "he,him,his,himself,false",
    "he,him,his,himself,false",
    "he,him,his,himself,false",
    "he,him,his,himself,false",
    "it,it,its,itself,false",
    "it,it,its,itself,false",
    "she,her,her,herself,false",
    "she,her,her,herself,false",
    "she,her,her,herself,false",
    "she,her,her,herself,false",
    "she,her,her,herself,false",
    "they,them,their,themselves,true",
    "they,them,their,themselves,true",
    "🐱,🐱,🐱s,🐱self,false",
]
